require:
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - "*.log"
    - bin/**/*

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "spec/**/*"
Metrics/MethodLength:
  Exclude:
    - 'lib/game_manager.rb'
